// client/src/components/PDFReport.jsx

import React from 'react';

const PDFReport = ({ taxData, gstData, userProfile }) => {
  const generatePDF = async () => {
    // Using html2pdf.js - add to your project: npm install html2pdf.js
    const html2pdf = (await import('html2pdf.js')).default;
    
    const reportHTML = `
      <div style="font-family: 'Segoe UI', sans-serif; padding: 40px; max-width: 800px;">
        <div style="text-align: center; margin-bottom: 30px;">
          <h1 style="color: #10b981; margin: 0;">📊 EconSim</h1>
          <p style="color: #666; margin: 5px 0;">Policy Impact Report</p>
          <p style="color: #999; font-size: 12px;">Generated on ${new Date().toLocaleDateString('en-IN', { dateStyle: 'long' })}</p>
        </div>
        
        <div style="background: linear-gradient(135deg, #f0fdf4 0%, #ecfeff 100%); padding: 20px; border-radius: 12px; margin-bottom: 20px;">
          <h2 style="color: #047857; margin-top: 0;">💰 Income Tax Summary (FY 2025-26)</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; color: #666;">Annual Income</td>
              <td style="padding: 8px 0; text-align: right; font-weight: bold;">₹${taxData.income?.toLocaleString('en-IN') || 0}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #666;">Recommended Regime</td>
              <td style="padding: 8px 0; text-align: right; font-weight: bold; color: #10b981;">${taxData.betterRegime?.toUpperCase() || 'NEW'} REGIME</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #666;">Tax Payable</td>
              <td style="padding: 8px 0; text-align: right; font-weight: bold;">₹${taxData.totalTax?.toLocaleString('en-IN') || 0}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #666;">Effective Tax Rate</td>
              <td style="padding: 8px 0; text-align: right; font-weight: bold;">${taxData.effectiveRate?.toFixed(2) || 0}%</td>
            </tr>
            <tr style="border-top: 1px solid #ddd;">
              <td style="padding: 12px 0; color: #666;">Savings vs Other Regime</td>
              <td style="padding: 12px 0; text-align: right; font-weight: bold; color: #10b981; font-size: 18px;">₹${taxData.savings?.toLocaleString('en-IN') || 0}</td>
            </tr>
          </table>
        </div>

        <div style="background: linear-gradient(135deg, #fff7ed 0%, #fef3c7 100%); padding: 20px; border-radius: 12px; margin-bottom: 20px;">
          <h2 style="color: #c2410c; margin-top: 0;">🛒 Monthly GST Impact</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; color: #666;">Total Monthly Spending</td>
              <td style="padding: 8px 0; text-align: right; font-weight: bold;">₹${gstData.totalExpense?.toLocaleString('en-IN') || 0}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #666;">GST Paid (Monthly)</td>
              <td style="padding: 8px 0; text-align: right; font-weight: bold; color: #f59e0b;">₹${gstData.totalGST?.toLocaleString('en-IN') || 0}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #666;">GST Paid (Annual)</td>
              <td style="padding: 8px 0; text-align: right; font-weight: bold; color: #f59e0b;">₹${((gstData.totalGST || 0) * 12).toLocaleString('en-IN')}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #666;">Effective GST Rate</td>
              <td style="padding: 8px 0; text-align: right; font-weight: bold;">${gstData.effectiveRate?.toFixed(1) || 0}%</td>
            </tr>
          </table>
        </div>

        <div style="background: #f8fafc; padding: 20px; border-radius: 12px; margin-bottom: 20px;">
          <h2 style="color: #475569; margin-top: 0;">📝 Tax Saving Tips</h2>
          <ul style="color: #666; line-height: 1.8;">
            ${taxData.betterRegime === 'new' ? `
              <li>New Regime is best for you - no need for tax-saving investments</li>
              <li>Focus on high-return investments instead of tax-saving ones</li>
              <li>Your income up to ₹12.75L is effectively tax-free with standard deduction</li>
            ` : `
              <li>Maximize Section 80C investments (₹1.5L limit)</li>
              <li>Get health insurance for 80D deduction (up to ₹50K)</li>
              <li>Consider NPS for additional ₹50K deduction under 80CCD(1B)</li>
            `}
          </ul>
        </div>

        <div style="text-align: center; color: #999; font-size: 11px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee;">
          <p>Generated by EconSim - Policy Impact Simulator</p>
          <p>Data based on Union Budget 2025-26 and GST 2.0 (Sept 2025)</p>
          <p style="color: #ccc;">This is for informational purposes only. Consult a tax professional for advice.</p>
        </div>
      </div>
    `;

    const element = document.createElement('div');
    element.innerHTML = reportHTML;

    const opt = {
      margin: 10,
      filename: `EconSim_Tax_Report_${new Date().toISOString().split('T')[0]}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(element).save();
  };

  return (
    <div className="flex justify-center w-full"> {/* ADDED WRAPPER FOR CENTERING */}
      <button
        onClick={generatePDF}
        className="flex items-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-red-500 to-orange-500 text-white font-semibold hover:shadow-lg hover:shadow-red-500/25 transition-all"
      >
        📄 Download PDF Report
      </button>
    </div>
  );
};

export default PDFReport;